[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
bevy_asset_loader = "0.11.0"
bevy_egui = "0.14"
bevy-inspector-egui = { version = "0.11.0", optional = true }
# bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
serde= "1.0.137"
serde_json="1.0.81"
bevy_prototype_lyon = "0.5.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
indexmap = "1.9.1"
bevy_screen_diags = "0.4.0"
euclid = { features = ["serde"], version = "0.22.7"}
# heron = { version = "3", features = ["2d"] }

[features]
default = []
debug = ["bevy-inspector-egui"]

[workspace]
resolver = "2"
