[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
bevy_egui = "0.28.0"
bevy-inspector-egui = { version = "0.25.2" }
serde= "1.0.207"
serde_json="1.0.124"
bevy_prototype_lyon = "0.12.0"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
indexmap = "2.4.0"
euclid = { features = ["serde"], version = "0.22.10"}
rand = "0.8.5"

[workspace]
resolver = "2"
