[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
bevy_asset_loader = "0.10.0"
bevy_egui = "0.14"
bevy-inspector-egui = { version = "0.10.0", optional = true }

[features]
default = []
debug = ["bevy-inspector-egui"]
