[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
bevy_asset_loader = "0.10.0"
bevy_egui = "0.14"
bevy-inspector-egui = { version = "0.11.0", optional = true }
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
serde= "1.0.137"
serde_json="1.0.81"

[features]
default = []
debug = ["bevy-inspector-egui"]

[workspace]
resolver = "2"
