[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy_egui = "0.19"
bevy-inspector-egui = { version = "0.17", optional = true }
serde= "1.0"
serde_json="1.0"
bevy_prototype_lyon = "0.7"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
indexmap = "1.9"
euclid = { features = ["serde"], version = "0.22"}
rand = "0.8"

[features]
debug = ["bevy-inspector-egui"]

[workspace]
resolver = "2"
