[package]
name = "base-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_egui = "0.22"
bevy-inspector-egui = { version = "0.20" }
serde= "1.0"
serde_json="1.0"
bevy_prototype_lyon = "0.9"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"
indexmap = "2.0"
euclid = { features = ["serde"], version = "0.22"}
rand = "0.8"

[workspace]
resolver = "2"
