// Central tuning values for game balance. Adjust numbers here first.

pub const START_ENERGY: f32 = 1000.;
pub const START_MATERIALS: f32 = 1000.;
pub const INITIAL_WAVE_DELAY_SECS: f32 = 1.;
pub const NEXT_WAVE_DELAY_SECS: f32 = 1.;
pub const GAME_OVER_COUNTDOWN_SECS: u64 = 60;

pub const LASER_TOWER_ENERGY_COST: f32 = 100.;
pub const LASER_TOWER_MATERIALS_COST: f32 = 150.;
pub const LASER_DAMAGE_PER_SECOND: f32 = 100.;
pub const LASER_RANGE_RADIUS: f32 = 1.5;
pub const LASER_SHOT_DURATION_SECS: f32 = 1.;
pub const LASER_RELOAD_DURATION_SECS: f32 = 1.;

pub const ROCKET_TOWER_ENERGY_COST: f32 = 400.;
pub const ROCKET_TOWER_MATERIALS_COST: f32 = 350.;
pub const ROCKET_DAMAGE: f32 = 250.;
pub const ROCKET_DAMAGE_RADIUS: f32 = 0.65;
pub const ROCKET_RANGE_RADIUS: f32 = 3.5;
pub const ROCKET_SPEED_TILES_PER_SECOND: f32 = 3.;
pub const ROCKET_FUEL_RANGE_TILES: f32 = 5.;
pub const ROCKET_FUEL_CONSUMPTION_PER_SECOND: f32 = 1.;
pub const ROCKET_RELOAD_DURATION_SECS: f32 = 4.5;
pub const ROCKET_SHOOT_DURATION_SECS: f32 = 1.;

pub const POWER_PLANT_ENERGY_COST: f32 = 300.;
pub const POWER_PLANT_MATERIALS_COST: f32 = 150.;
pub const POWER_PLANT_BUFFER_SIZE: f32 = 50.;
pub const POWER_PLANT_ENERGY_PER_SECOND: f32 = 10.;

pub const FACTORY_ENERGY_COST: f32 = 400.;
pub const FACTORY_MATERIALS_COST: f32 = 300.;
pub const FACTORY_ENERGY_BUFFER_SIZE: f32 = 10.;
pub const FACTORY_ENERGY_PER_SECOND: f32 = 4.;
pub const FACTORY_MATERIALS_BUFFER_SIZE: f32 = 5.;
pub const FACTORY_MATERIALS_PER_SECOND: f32 = 2.;

pub const NORMAL_ENEMY_SIZE_RADIUS: f32 = 0.125;
pub const NORMAL_ENEMY_SPEED_TILES_PER_SECOND: f32 = 1.;
pub const NORMAL_ENEMY_HEALTH: f32 = 100.;

pub const SPEEDER_ENEMY_SIZE_RADIUS: f32 = 0.075;
pub const SPEEDER_ENEMY_SPEED_TILES_PER_SECOND: f32 = 2.;
pub const SPEEDER_ENEMY_HEALTH: f32 = 10.;

pub const TANK_ENEMY_SIZE_RADIUS: f32 = 0.25;
pub const TANK_ENEMY_SPEED_TILES_PER_SECOND: f32 = 0.5;
pub const TANK_ENEMY_HEALTH: f32 = 800.;

pub const ENEMY_BREAK_RADIUS_PADDING_FACTOR: f32 = 0.1;
pub const ENEMY_KILL_MATERIAL_REWARD_DIVISOR: f32 = 5.;
pub const ENEMY_BASE_DAMAGE_MULTIPLIER: f32 = 5.;
pub const ENEMY_DEATH_EXPLOSION_RADIUS_FACTOR: f32 = 1.2;
pub const ENEMY_DEATH_EXPLOSION_DAMAGE_DIVISOR: f32 = 20.;

pub const WAVE_BASE_ENEMY_COUNT: u32 = 3;
pub const WAVE_ENEMIES_PER_WAVE: u32 = 2;
pub const WAVE_START_ENEMY_SPAWN_INTERVAL_SECS: f32 = 0.8;
pub const WAVE_ENEMY_SPAWN_INTERVAL_DECREASE_PER_WAVE_SECS: f32 = 0.05;
pub const WAVE_MIN_ENEMY_SPAWN_INTERVAL_SECS: f32 = 0.35;
pub const TANK_SPAWN_EVERY_NTH_ENEMY: u32 = 10;
